import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import { AuthContextProvider } from "@/context/AuthentificationContext";
import { PiHandWavingThin } from "react-icons/pi";
import { TbFaceIdError } from "react-icons/tb";
import { GameTableContextProvider } from "@/context/GameTableContext";

const roboto = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Note Sharing",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
            </head>
            <body className={roboto.className + " overflow-hidden"}>
                <AuthContextProvider>
                    <Navbar />
                    <div className="w-full h-screen overflow-y-auto py-10 px-5">
                        <Toaster
                            position="top-right"
                            gutter={8}
                            toastOptions={{
                                className: "",
                                duration: 3000,
                                style: {
                                    background: "#363636",
                                    color: "#fff",
                                },
                                success: {
                                    icon: <PiHandWavingThin className="text-3xl"/>,
                                    style: {
                                        backgroundColor: "#355e3b",
                                        padding: "25px",
                                    },
                                },
                                error: {
                                    icon: <TbFaceIdError className="text-3xl"/>,
                                    style: {
                                        backgroundColor: "#800000",
                                        padding: "25px",
                                    },
                                },
                            }}
                        />
                        <GameTableContextProvider>
                            {children}
                        </GameTableContextProvider>
                    </div>
                </AuthContextProvider>
            </body>
        </html>
    );
}
